const tNO = "tNO";
const tYES = "tYES";
//            <EnumType Name="BoActivities">
const cn_Conversation = "cn_Conversation";
const cn_Meeting = "cn_Meeting";
const cn_Task = "cn_Task";
const cn_Other = "cn_Other";
const cn_Note = "cn_Note";
const cn_Campaign = "cn_Campaign";
